apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app2
  namespace: flux-system
spec:
  interval: 1m
  path: .
  sourceRef:
    kind: GitRepository
    name: flux-dev2
  targetNamespace: dev2
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
